// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnLAE8-08NV0EXmdqwQt57XCA1yol2O9s',
    appId: '1:320874863769:web:2f21dd38f152e467196c08',
    messagingSenderId: '320874863769',
    projectId: 'my-project-b49e1',
    authDomain: 'my-project-b49e1.firebaseapp.com',
    storageBucket: 'my-project-b49e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH4RtGR7fSsP2V-9fy1rhaFx_p_-ohi1A',
    appId: '1:320874863769:android:ad496bdf6a307033196c08',
    messagingSenderId: '320874863769',
    projectId: 'my-project-b49e1',
    storageBucket: 'my-project-b49e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVzBVZdrPONmV7YrDHFq7sEf-8iHNzgWc',
    appId: '1:320874863769:ios:9819967aa5e553cc196c08',
    messagingSenderId: '320874863769',
    projectId: 'my-project-b49e1',
    storageBucket: 'my-project-b49e1.firebasestorage.app',
    iosBundleId: 'com.example.ecomMultiStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVzBVZdrPONmV7YrDHFq7sEf-8iHNzgWc',
    appId: '1:320874863769:ios:9819967aa5e553cc196c08',
    messagingSenderId: '320874863769',
    projectId: 'my-project-b49e1',
    storageBucket: 'my-project-b49e1.firebasestorage.app',
    iosBundleId: 'com.example.ecomMultiStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnLAE8-08NV0EXmdqwQt57XCA1yol2O9s',
    appId: '1:320874863769:web:8f606f8662c7cb5a196c08',
    messagingSenderId: '320874863769',
    projectId: 'my-project-b49e1',
    authDomain: 'my-project-b49e1.firebaseapp.com',
    storageBucket: 'my-project-b49e1.firebasestorage.app',
  );
}
